// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// init_adj_matrix_cpp
arma::sp_mat init_adj_matrix_cpp(arma::sp_mat adj_matrix, Rcpp::NumericMatrix contact_matrix, Rcpp::IntegerVector category_id, Rcpp::NumericVector num_contacts, Rcpp::IntegerVector sample_order, bool display_progress);
RcppExport SEXP _asclepius_init_adj_matrix_cpp(SEXP adj_matrixSEXP, SEXP contact_matrixSEXP, SEXP category_idSEXP, SEXP num_contactsSEXP, SEXP sample_orderSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type adj_matrix(adj_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type contact_matrix(contact_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type category_id(category_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type num_contacts(num_contactsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_order(sample_orderSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(init_adj_matrix_cpp(adj_matrix, contact_matrix, category_id, num_contacts, sample_order, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_asclepius_init_adj_matrix_cpp", (DL_FUNC) &_asclepius_init_adj_matrix_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_asclepius(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
